# Generated by Django 4.0.5 on 2022-10-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_trxn_id'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='txn_id',
            field=models.OneToOneField(help_text='Transaction ID is the unique code that Can Be Used To Track the status of an Order', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.order'),
        ),
    ]
