# Generated by Django 4.0.5 on 2022-09-25 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('trxn_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date of Order')),
                ('total', models.IntegerField(verbose_name='Total of Purchase')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
