# Generated by Django 4.0.5 on 2022-09-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.JSONField(default='"Sample"'),
        ),
    ]
