# Generated by Django 4.0.5 on 2022-09-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
    ]
