# Generated by Django 4.0.5 on 2022-09-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
