# Generated by Django 4.0.5 on 2022-10-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trxn_id',
            field=models.CharField(max_length=70, primary_key=True, serialize=False, verbose_name='Transaction ID'),
        ),
    ]
