# Generated by Django 4.0.5 on 2022-10-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_trxn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trxn_id',
            field=models.CharField(default='ff4ba52e84852014bd73c4496a30db73ecc3182880abc13acd69831b2e083481d579', max_length=70, primary_key=True, serialize=False, verbose_name='Transaction ID'),
        ),
    ]
