# Generated by Django 4.0.5 on 2022-10-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_trxn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trxn_id',
            field=models.CharField(default='TRXN015b15fbe8307cf7dfa5', max_length=70, primary_key=True, serialize=False, verbose_name='Transaction ID'),
        ),
    ]
