# Generated by Django 4.0.5 on 2022-10-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_trxn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amt_payable',
            field=models.IntegerField(blank=True, help_text='Amount to be payed with Charges Included', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(help_text='Total of Goods Purchased Without Any Charges', verbose_name='Total of Purchase'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trxn_id',
            field=models.CharField(default='TRXN6ba19dfc72b871b4c85d', max_length=70, primary_key=True, serialize=False, verbose_name='Transaction ID'),
        ),
    ]
