# Generated by Django 4.0.5 on 2022-10-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_amt_payable_alter_order_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trxn_id',
            field=models.CharField(default='TRXN4f3d9dd6992dae7af4315533', max_length=70, primary_key=True, serialize=False, verbose_name='Transaction ID'),
        ),
    ]
