# Generated by Django 4.0.5 on 2022-10-03 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Products Description')),
                ('product_category', models.CharField(choices=[('hot_deals', 'Hot Deals'), ('top_discounts', 'Top Discounts'), ('perishables', 'Perishables'), ('fruits', 'Fruits'), ('food items', 'Food Items'), ('spices', 'Spices'), ('vegetables', 'Vegetables'), ('naija ingredients', 'Naija Ingredients'), ('drinks', 'Drinks'), ('oil and sauce', 'Oil and Sauce'), ('baby', 'Baby and Kids'), ('snacks', 'Snacks'), ('toiletries', 'Toiletries'), ('food stuffs', 'Food Stuffs'), ('yam', 'Yam'), ('rice', 'Rice'), ('beans', 'Beans'), ('garri', 'Garri')], max_length=30)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight in Kg')),
                ('size', models.CharField(blank=True, choices=[('extra_small', 'Extra Small'), ('small', 'Small'), ('medium', 'Medium'), ('big', 'Big'), ('large', 'Large'), ('extra_large', 'Extra Large')], max_length=50, null=True, verbose_name='Size of Product')),
                ('price', models.IntegerField(default=10, help_text='Enter Price in Naira')),
                ('qty', models.IntegerField(default=0, verbose_name='Quantity')),
                ('perishable', models.BooleanField(default=False, verbose_name='Is This A Perishable Good(s)?')),
                ('product_picture', models.ImageField(help_text='Upload a Clear Picture of the Product', upload_to='products')),
                ('availability', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('pending', 'Pending')], default=True, max_length=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
