# Generated by Django 4.0.5 on 2022-10-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Weight (Specify the Units)'),
        ),
    ]
