# Generated by Django 4.0.5 on 2022-10-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, help_text='Percentage of Discount (If Available)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Price Without Discount (If Available)'),
        ),
    ]
