# Generated by Django 4.0.5 on 2022-10-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_qty_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, help_text='Enter Price in Naira'),
        ),
    ]
