# Generated by Django 4.0.5 on 2022-10-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_customuser_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(default=0, verbose_name='Phone Number'),
        ),
    ]
