# Generated by Django 4.0.5 on 2022-10-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='addional_phone_no',
            new_name='additional_phone_no',
        ),
    ]
