# Generated by Django 4.0.5 on 2022-10-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_rename_addional_phone_no_customuser_additional_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('none', 'Prefer Not to Specify')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='services',
            field=models.CharField(blank=True, help_text='What Services do you intend to offer Play?', max_length=15, null=True),
        ),
    ]
