# Generated by Django 4.0.5 on 2022-10-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_customuser_gender_alter_customuser_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('not_approved', 'Not Approved')], default='pending', help_text='Status of Partner Request', max_length=15, null=True),
        ),
    ]
