# Generated by Django 4.0.5 on 2022-10-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('not_approved', 'Not Approved')], help_text='Status of Partner Request', max_length=15, null=True),
        ),
    ]
