# Generated by Django 4.0.5 on 2022-10-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_customuser_region_of_del_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='status',
            new_name='partnership_status',
        ),
    ]
