# Generated by Django 4.0.5 on 2022-10-08 09:43

import User.random_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_rename_status_customuser_partnership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=User.random_id.random_generator, max_length=50, primary_key=True, serialize=False),
        ),
    ]
