# Generated by Django 4.0.5 on 2022-10-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='c964ea1b0d659152b524', max_length=50, primary_key=True, serialize=False),
        ),
    ]
